title:            Biagio La Rosa
tagline: Personal academic site of Biagio La Rosa
description:      Bio, interests (especially on Explainable Artificial Intelligence) and news about Biagio La Rosa. 
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://biagiomattialarosa.github.io
#http://localhost:5000
#https://jponttuset.github.io

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: biagiomattialarosa
# Owner/author information
owner:
  name:           Biagio Mattia La Rosa
  avatar:         me.jpg
  bio:            I am a PhD student on Computer Engineering @ sapienza. My focus is to study methodologies to improve the interpretability of Deep Learning techniques. Passionate also about neuroscience, psychology, games, and astronomy.
  email:          larosa AT diag.uniroma1.it
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: larosabiagio
  linkedin: larosabiagio
  google_scholar: qzonkqcAAAAJ
  google_plus: 
  github: biagiomattialarosa
# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: News
    url: /news/
  - title: Collaborate
    url: /collaborate/
  - title: Publications
    url: /publications/
#  - title: Cv
#    url: /cv/
#  - title: Code
#    url: /code/
#  - title: Blog
#    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Zurich
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag